### ISSUE TITLE
The future of the cod

### ISSUE THREAD

**Issue by may17** [contao/official-demo#105]
Dear cod folks,

Seems like there are some people who will work on a cod v2 and i will stop investigating any work on the cod. Time to talk about the future of the project and involve everyone who's intrested.

**Organization**
I will stop any work on this project in 2022. This means we need a new project lead. How about you @sascha-mueller, would be still part of the cod team?

**Current Maintaining**
Currently only @cliffparnitzky is an active maintainer. @cliffparnitzky am i right that you only like to maintain and won't bei part of the creation of a new demo? 

Anyone else please comment here If you like to be part  of the team and being ntrested to work on a new CoD version.

Todos:

- [x] Find new project lead / leads
- [x] clarify if @sascha-mueller will stay in the project
- [x] clarify the future role of @cliffparnitzky in the project
- [x] Add new members to the GitHub repo and kick ex members.

**Comment by sascha-mueller** [comment]
@may17  As far as foreseeable I will stay in the project. In a future version I would see myself responsible for the SCSS again.

**Comment by fkaminski** [comment]
I will follow the further development (v2) in the future. Should I then be able to contribute something (not as maintainer) I will try to do so with pleasure.

**Comment by fkaminski** [comment]
First of all, I would like to thank Joe for his work so far. 
As mentioned, there should be a leader here who can make final decisions. 
Otherwise, one will surely hang unnecessarily on various issues.

Optimally, this person should be familiar with GitHub in terms of maintenance/merging, etc..
Would @cliffparnitzky continue to fill this role?

**Comment by fkaminski** [comment]
Furthermore, the next step should be to first agree on basic questions regarding v2  
and then respond accordingly.

I had tried, from my point of view, to put these up for discussion in #103. 
This is primarily about:

- How to maintain most effectively (regarding Contao version/installation).
- This depends on: Fundamental task of COD
- Together then appropriate implementations (content/layout).

Maybe it would be better to split them into separate issues?

**Comment by fkaminski** [comment]
@sascha-mueller Bist du über Slack erreichbar?

**Comment by may17** [comment]
Any news @fkaminski @sascha-mueller ?

**Comment by sascha-mueller** [comment]
@may17 
Cliff has not yet commented. Franko is out for now, because he is busy with other projects for Contao.
Franko and I decided to leave the content as it is and only change the layout.
Currently no one has been found for the creation of a design. Therefore it is a consideration to orientate on the current camp page.

**Comment by fkaminski** [comment]
> Therefore it is a consideration to orientate on the current camp page.
As discussed on Slack, I think a layout implementation based on the current camp layout is good, as long as no one else presents a different layout concept.

**Comment by may17** [comment]
You reconized that the camp page is based on a theme from Contao-Themes.net? So creating a copy of an existing theme is maybe not a good approach for an official demo?

**Comment by sascha-mueller** [comment]
@may17 Yes, I know that it is a theme. It's also not about copying, but just a general inspiration.

Currently I'm also talking with my employer to see what he wants to contribute to the theme.

**Comment by fkaminski** [comment]
> So creating a copy of an existing theme is maybe not a good approach for an official demo?

As Sascha mentioned it was intended more as a layout inspiration in this regard.

**Comment by may17** [comment]
Ok thats up to you. As mentioned in the issue i will not bei longer responsible for the CoD. I started an internal discussion on the slack now to figure out how to move on cause there was no clear response who will take the project lead in future.

**Comment by Tastaturberuf** [comment]
yesterday i was thinking about the demo when it came to test the 4.13. i think the demo is too complicated to install and maintain. i would like to test the possibilities of https://github.com/richardhj/contao-theme-framework and maybe we will find a new solution here. @richardhj can you see any chance we can use your framework for easier maintain the demo?

**Comment by richardhj** [comment]
The charm of the Theme Framework is that it standardizes themes, in the sense of where you find the templates, CSS files, etc. pp., and that it comes with Encore that IMHO will be the new standard since it comes from the Symfony Ecosystem.

The framework is a CAN but not a MUST for the Contao demo.
To be honest, I would wait for any progress in contao/contao#2781 before making a decision. Also, to have the best forward compatibility.

However, the Contao demo is highly dependent on the database. I don't know what an official strategy might look like, but using the official database commands from contao/contao#3631 for the Contao demo would be a great benefit already.

**Comment by fkaminski** [comment]
@richardhj :-)
But: First things first. 
I would favor it if we first _internally_ agree on a layout (for the purpose of representative representation) that @sascha-mueller  could implement. 
Subsequently, then accompanied by possible further deployment options...

**Comment by may17** [comment]
Could we please stay focused on the main concerns of this issue please ;)

**Comment by sascha-mueller** [comment]
To finally move Joe's cause forward:
If no one wants, I will take over the further organization of the COD for the time being. However, help is welcome.
Cliff remains in the team and primarily takes care of the change from one version to the next.

**Comment by may17** [comment]
Nice to read about your decision @sascha-mueller :) @leofeyer could you please remove me from the official demo team and add @sascha-mueller instead? I also created a pull request to update the README.md.
